---
title             : "**Article Processing Charges: Gateways or Gatekeepers of Author Diversity? OR Article Processing Charges alter the geographic representation of authors in Open Access journals**"
shorttitle        : "APCs and Author Diversity "

author: 
  - name          : "Audrey C. Smith"
    affiliation   : "1"
    role:         
      - Methodology
      - Investigation
      - Writing - Original Draft
      - Writing - Review & Editing
  - name          : "Leandra Merz"
    affiliation   : "1"
    role:
      - Methodology
      - Investigation
      - Writing - Original Draft
      - Writing - Review & Editing
  - name          : "Jesse Borden"
    affiliation   : "2"
    role:
      - Methodology
      - Investigation
      - Software
      - Writing - Review & Editing
  - name          : "Chris Gulick"
    affiliation   : "3"
    role:
      - Methodology
      - Investigation
      - Writing - Review & Editing
  - name          : "Akhil Kshirsagar"
    affiliation   : "1"
    role:
      - Methodology
      - Investigation
      - Writing - Review & Editing
  - name          : "Emilio M. Bruna"
    affiliation   : "3,4"
    corresponding : no    # Define only one corresponding author
    address       : "Center for Latin American Studies, University of Florida, PO Box 115530, Gainesville, Florida, 32611 USA"
    email         : "embruna@ufl.edu"
    role:
      - Conceptualization
      - Methodology
      - Data collection
      - Software
      - Data Curation
      - Writing - Original Draft
      - Writing - Review & Editing
      - Supervision

affiliation:
  - id            : "1"
    institution   : "Department of Geography, University of Florida"
  - id            : "2"
    institution   : "School for Natural Resources and the Environment, University of Florida"
  - id            : "3"
    institution   : "Department of Wildlife Ecology and Conservation, University of Florida"
  - id            : "4"
    institution   : "Center for Latin American Studies, University of Florida"

authornote: |
  A. Smith, Department of Geography, University of Florida, PO Box 117315, Gainesville, Florida, 32611 USA
  
  L. Merz, Department of Geography, University of Florida, PO Box 117315, Gainesville, Florida, 32611 USA
  
  A. Kshirsagar, Department of Geography, University of Florida, PO Box 117315, Gainesville, Florida, 32611 USA
  
  J. Borden, School for Natural Resources and the Environment, University of Florida, PO Box 116455, Gainesville, Florida, 32611 USA
  
  C. Gulick, Department of Wildlife Ecology and Conservation, University of Florida, PO Box 110430, Gainesville, Florida, 32611 USA
  
  E. M. Bruna, Department of Wildlife Ecology and Conservation, University of Florida, PO Box 110430, Gainesville, Florida, 32611 USA and Center for Latin American Studies, University of Florida, PO Box 115530, Gainesville, Florida, 32611 USA
  
  A. Smith and L. Merz are contributed equally to this manuscript.
  
  We thank N. Emery, C. Scott, and D. Forero for assistance in gathering preliminary data for the project and ---- for helpful discussions and feedback on the manuscript.

abstract: |
 To be added last.
  
keywords: "article processing charges, author diversity, Global South, geographic diversity, mirror journals, open access"

wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : "papaja::apa6_pdf"

---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")

library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(stringr)
library(kableExtra)
library(readr)
```



```{r analysis-preferences}
# # Seed for random number generation
# set.seed(42)
# knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

# Introduction

# Methods
$$D^2 = \frac{1}{\Sigma_{i-1}^R * p_i^2}$$


We used `r cite_r("r-references.bib")` for all our analyses.

# Results

# Discussion



\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup

<!-- \newpage -->
<!-- ```{r child = "Smith_etal_FigsTables.Rmd"} -->
<!-- ``` -->

\newpage
# Appendix
<!-- ```{r child = "Smith_etal_Appendix.Rmd"} -->
<!-- ``` -->
