

```{r FigA1,fig.align='center',fig.cap=paste("Percentage of lead authors (i..e, first and single-authors) based in different countries; Parent and Mirror journals combined. Numbers adjacent to bars are the number of articles with lead authors based in that country."), message = FALSE,warning=FALSE}

source("./Rscript/functions_ms/AppFig1.R")

AppFig1(AllData)
```

```{=tex}
\newpage
\blandscape
```

```{r FigA2,echo=FALSE, message = FALSE,warning=FALSE, fig.align='center',fig.cap=paste("The effect on $D_{2}$ of excluding authors from individual countries (B) The effect on $D_{2}$ of excluding authors from individual countries after having first removed China."),fig.height = 16,fig.width=24}
source("./Rscript/functions_ms/Country_removal_div_fig.R")
removal <- Country_removal_div_fig()
p1 <- removal[[1]]
p2 <- removal[[2]]
grid.arrange(p1, p2, ncol = 1)
```

```{=tex}
\elandscape
\newpage
```

```{r FigA3, echo=FALSE, message = FALSE,warning=FALSE, fig.align='center', fig.cap=paste("Results of permutation tests comparing author Diversity, Richness, and Evenness of open access articles published in Parent and Mirror journals. The line indicates the observed difference between the two populations, while the bars represent the frequency in 5000 permutations of the difference between two groups identical in size and structure to the observed collections but to which articles were assigned at random without replacement. Results are shown for analyses including all countries (A-C) and when excluding artciles by first- and single-authors based in China or the USA (D-F)."), fig.fullwidth=TRUE,message = FALSE,warning=FALSE}

knitr::opts_knit$set(eval.after = "fig.cap")
source("./Rscript/functions_ms/permutation_tests_OA_fig.R")
All_boots_wide <- read_csv("./output/MirrorvOAinPW_permutations.csv")
Perm_test <- permutation_tests_OA_fig(All_boots_wide, AllData)
P_FIG <- Perm_test[[1]]
P_FIG
```


```{r FigA4,fig.align='center', fig.cap=paste("Author Geographic Diversity (Shannon's Index) for N = ", insert_custom1, " articles in Mirror journals (solid line) and 1000 identically sized collections generated by selecting an identical number of non-open access articles in Parent journals by bootstrapping from the pool of N = ",insert_custom2, " total articles. Results are shown for analyses including all countries (A, C) and when excluding artciles by first- and single-authors based in China or the USA (B, D)."), fig.fullwidth=TRUE,message = FALSE,warning=FALSE}

source("./Rscript/functions_ms/DivBootFig_shannon.R")
DivBootFig_shannon(
  BootMirror_RichDiv,
  single_ALL,
  first_ALL,
  single_NOCHNUSA,
  first_NOCHNUSA
)
```

```{r FigA5,fig.align='center', fig.cap=paste("Proportion of lead authors based in different World Bank Lending Groups when pooling all of the (A) N = ", insert_custom1, " articles in open access (OA) Mirror journals, (B) N =  ",insert_custom3, " OA articles in Parent journals, and (C) N =  ",insert_custom2, " non-OA articles in Parent journals."),fig.fullwidth=TRUE,fig.height = 18,fig.width=16, message = FALSE,warning=FALSE}
source("./Rscript/functions_ms/AppFig3.R")
AppFig3(AllData, "author_first")
```

```{=tex}
\newpage
\blandscape
```

```{r TableA1, echo=FALSE,message = FALSE,warning=FALSE}
WaiverCountries <- read.csv("./data_clean/WaiverCountries.csv")
NON_WavierCountries <- read.csv("./data_clean/NON_WavierCountries.csv")


NON_WavierCountries$WaiverGroup <- "no waiver"

waiver_table2 <- bind_rows(WaiverCountries, NON_WavierCountries) %>%
  arrange(IncomeGroup, desc(WaiverGroup), Region, Country)

waiver_table2$IncomeGroup <- as.character(waiver_table2$IncomeGroup)
waiver_table2$IncomeGroup <- gsub("Upper middle income", "Middle income", waiver_table2$IncomeGroup)
waiver_table2$IncomeGroup <- gsub("Lower middle income", "Middle income", waiver_table2$IncomeGroup)

waiver_table2$IncomeGroup <- ordered(waiver_table2$IncomeGroup,
  levels = c(
    "Low income",
    "Middle income",
    "High income"
  )
)




waiver_table2$WaiverGroup <- gsub("GroupA", "A - 100%", waiver_table2$WaiverGroup)
waiver_table2$WaiverGroup <- gsub("GroupB", "B - 50%", waiver_table2$WaiverGroup)

waiver_table2$WaiverGroup <- ordered(waiver_table2$WaiverGroup,
  levels = c(
    "A - 100%",
    "B - 50%",
    "no waiver"
  )
)
#
#
waiver_table2$group <- NA



waiver_table2$Region <- as.factor(waiver_table2$Region)
waiver_table2$Region <- ordered(waiver_table2$Region,
  levels = c(
    "South Asia",
    "Sub-Saharan Africa",
    "Latin America & Caribbean",
    "Middle East & North Africa",
    "East Asia & Pacific",
    "Europe & Central Asia",
    "North America"
  )
)



waiver_table2$Region[waiver_table2$Country == "Tokelau"] <- "East Asia & Pacific"
waiver_table2$Region[waiver_table2$Country == "Niue"] <- "East Asia & Pacific"
waiver_table2$Region[waiver_table2$Country == "Cook Islands"] <- "East Asia & Pacific"
waiver_table2$Region[waiver_table2$Country == "Saint Helena"] <- "Europe & Central Asia"


levels(waiver_table2$Region)[levels(waiver_table2$Region) == "South Asia"] <- "1South Asia"
levels(waiver_table2$Region)[levels(waiver_table2$Region) == "Sub-Saharan Africa"] <- "2Sub-Saharan Africa"
levels(waiver_table2$Region)[levels(waiver_table2$Region) == "Latin America & Caribbean"] <- "3Latin America & Caribbean"
levels(waiver_table2$Region)[levels(waiver_table2$Region) == "Sub-Saharan Africa"] <- "4Sub-Saharan Africa"
levels(waiver_table2$Region)[levels(waiver_table2$Region) == "Middle East & North Africa"] <- "5Middle East & North Africa"
levels(waiver_table2$Region)[levels(waiver_table2$Region) == "East Asia & Pacific"] <- "6East Asia & Pacific"
levels(waiver_table2$Region)[levels(waiver_table2$Region) == "Europe & Central Asia"] <- "7Europe & Central Asia"
levels(waiver_table2$Region)[levels(waiver_table2$Region) == "North America"] <- "8North America"

waiver_table2$Country <- gsub("French part", "FRA", waiver_table2$Country)
waiver_table2$Country <- gsub("Federated", "Fed.", waiver_table2$Country)
waiver_table2$Country <- gsub("Lao People’s Democratic Republic", "Laos", waiver_table2$Country)
waiver_table2$Country <- gsub("United Republic of Tanzania", "Tanzania", waiver_table2$Country)
waiver_table2$Country <- gsub(" and ", " & ", waiver_table2$Country)
waiver_table2$Country <- gsub(" SAR China", "", waiver_table2$Country)
waiver_table2$Country <- gsub("Democratic Republic of the Congo", "Dem. Repub. Congo", waiver_table2$Country)
waiver_table2$Country <- gsub("of", "", waiver_table2$Country)
waiver_table2$Country <- gsub("Northern Mariana Islands", "N. Mariana Islands", waiver_table2$Country)


order_Region <- levels(waiver_table2$Region)

waiver_table2 <- waiver_table2 %>%
  select(Region, IncomeGroup, WaiverGroup, Country, group) %>%
  arrange(Region, IncomeGroup, WaiverGroup, Country) %>%
  group_by(Region, IncomeGroup, WaiverGroup) %>%
  mutate(group = replace(group, row_number() < 4, "1")) %>%
  mutate(group = replace(group, (row_number() > 3 & row_number() < 8), "2")) %>%
  mutate(group = replace(group, (row_number() > 7 & row_number() < 12), "3")) %>%
  mutate(group = replace(group, (row_number() > 11 & row_number() < 16), "4")) %>%
  mutate(group = replace(group, (row_number() > 15 & row_number() < 20), "5")) %>%
  mutate(group = replace(group, (row_number() > 19 & row_number() < 24), "6")) %>%
  mutate(group = replace(group, row_number() > 23, "7")) %>%
  group_by(Region, IncomeGroup, WaiverGroup, group) %>%
  summarize(CountryGroups = str_c(Country, collapse = ", ")) # this line takes the individual
# cells and collapses them into a single one



waiver_table2$Region <- as.character(waiver_table2$Region)

waiver_table2$Region <- gsub("East Asia", "E. Asia", waiver_table2$Region)
# waiver_table2$Region<-gsub("North","N.",waiver_table2$Region)
# waiver_table2$Region<-gsub("America","Am.",waiver_table2$Region)

waiver_table2$Region <- as.factor(waiver_table2$Region)

waiver_table2 <- waiver_table2 %>% spread(WaiverGroup, CountryGroups)
waiver_table2$group <- NULL
waiver_table3 <- waiver_table2 %>%
  arrange(Region, IncomeGroup) %>%
  group_by(Region, IncomeGroup) %>%
  mutate(IncomeGroup = replace(IncomeGroup, row_number() > 1, "")) %>%
  group_by(Region) %>%
  mutate(Region = replace(Region, row_number() > 1, ""))




waiver_table3 <- as.data.frame(waiver_table3)

names(waiver_table3) <- c("Region", "Income Group", "A - 100%", "B - 50%", "no waiver")

#


# waiver_table3$Country<-gsub("U.","\nU.",waiver_table3$Country)
# waiver_table3$Countries<-gsub("Turks","\nTurks",waiver_table3$Countries)
# waiver_table3$Countries<-gsub("Sudan","\nSudan",waiver_table3$Countries)
# waiver_table3$Country<-gsub("Somalia","\nSomalia",waiver_table3$Country)
# waiver_table3$Countries<-gsub("Sierra","\nSierra",waiver_table3$Countries)

waiver_table3$Region <- as.character(waiver_table3$Region)
waiver_table3$`Income Group` <- as.character(waiver_table3$`Income Group`)
waiver_table3$Region[is.na(waiver_table3$Region)] <- ""
waiver_table3$`Income Group`[is.na(waiver_table3$`Income Group`)] <- ""
waiver_table3[is.na(waiver_table3)] <- "-"

waiver_table3$Region <- str_replace(waiver_table3$Region, "[12345678]", "")



kable(waiver_table3,
  digits = 1,
  format = "latex",
  align = "c",
  row.names = FALSE,
  booktabs = T,
  linesep = "",
  # longtable = TRUE,
  caption = "Countries eligible for APC waivers through Elsevier's 'Research4Life' program by World Bank Global Region and Income Group."
) %>%
  kable_styling(
    bootstrap_options = c("hover"),
    latex_options = c(
      "scale_down",
      "repeat_header"
    ),
    full_width = F,
    font_size = 12,
    position = "left"
  ) %>%
  row_spec(2, extra_latex_after = "\\cline{1-5}") %>%
  row_spec(15, extra_latex_after = "\\cline{1-5}") %>%
  row_spec(25, extra_latex_after = "\\cline{1-5}") %>%
  row_spec(32, extra_latex_after = "\\cline{1-5}") %>%
  row_spec(42, extra_latex_after = "\\cline{1-5}") %>%
  row_spec(55, extra_latex_after = "\\cline{1-5}")
```

\elandscape

```{r TableA2, echo=FALSE,message = FALSE,warning=FALSE}
PermTable <- Perm_test[2]
PermTable <- as.data.frame(PermTable)

PermTable <- PermTable %>%
  mutate(countries = ifelse(countries == "all countries", "All Countries", countries))

PermTable <- PermTable %>%
  dplyr::rename("Obs. Diff." = "ObsDiff", "Metric" = "metric", "Countries" = "countries", "Parent (OA)" = "Subscription", "Mirror (OA)" = "Mirror")

# %>%
#   mutate(asterisk = ifelse((pval >= 97.5 |pval <= 2.5 ), "*", " "))
#
# PermTable$pval<-paste(PermTable$pval,PermTable$asterisk,sep="")
# PermTable$asterisk<-NULL
PermTable <- PermTable %>% select(Countries, Metric, `Mirror (OA)`, `Parent (OA)`, `Obs. Diff.`, pval)
PermTable <- PermTable %>% dplyr::rename("$\\hat{P}$" = "pval")

blank_row <- rep(NA, 6)
names(blank_row) <- names(PermTable)

all <- PermTable %>% filter(Countries == "All Countries")
not_all <- PermTable %>% filter(Countries == "China and USA excluded")
PermTable <- bind_rows(all, blank_row, not_all)


PermTable[2, 1] <- ""
PermTable[3, 1] <- ""
PermTable[6, 1] <- ""
PermTable[7, 1] <- ""


kable(PermTable,
  digits = 2,
  align = "llcccc",
  format = "latex",
  row.names = FALSE,
  escape = FALSE,
  booktabs = T,
  linesep = "", # removes the blank line after every 5 lines
  caption = "Results of permutation tests comparing the difference in diversity and richness of (A) articles in Mirror journals and (B) open access articles in parent journals."
) %>%
  kable_styling(
    bootstrap_options = c("hover"),
    full_width = F,
    latex_options = "scale_down",
    font_size = 12,
    position = "center"
  )
```


```{r TableA3, echo=FALSE,message = FALSE,warning=FALSE}
source("./Rscript/functions_ms/Table2.R")
Table2 <- Table2(
  single_ALL,
  single_NOCHNUSA,
  first_ALL,
  first_NOCHNUSA
)

Table2 <- Table2 %>%
  filter(Metric == "Evenness" | Metric == "Richness")

Table2 <- Table2 %>% arrange(Metric)

blank_row <- rep(NA, 9)
names(blank_row) <- names(Table2)
even <- filter(Table2, Metric == "Evenness")
rich <- filter(Table2, Metric == "Richness")


Table2 <- bind_rows(even, blank_row, rich)


Table2$Metric <- c(
  "Evenness", "", "", "",
  "",
  "Richness", "", "", ""
)

Table2$`OA Source` <- c(
  "Mirror", "", "Parent", "",
  "",
  "Mirror", "", "Parent", ""
)

colnames(Table2) <- c(
  "Metric",
  "Author",
  "OA",
  paste("Parent PW", "(mean \u00B1 SD)", sep = " "),
  "$\\hat{P}$",
  "Mirror",
  paste("Parent PW2", "(mean \u00B1 SD)", sep = " "),
  "$\\hat{P2}$",
  "OA Source"
)

Table2 <- Table2 %>% select(
  "Metric",
  "OA Source",
  "Author",
  "OA",
  "Parent PW (mean ± SD)",
  "$\\hat{P}$",
  "Mirror",
  "Parent PW2 (mean ± SD)",
  "$\\hat{P2}$"
)

Table2$OA <- as.character(Table2$OA)
Table2$OA <- gsub(".00", "", Table2$OA)
Table2$Mirror <- as.character(Table2$Mirror)
Table2$Mirror <- gsub(".00", "", Table2$Mirror)
#

colnames(Table2) <- c(
  "Metric",
  "OA Source",
  "Author",
  "OA",
  "Psub (mean ± SD)",
  "$\\hat{P}$",
  "OA",
  "Psub (mean ± SD)",
  "$\\hat{P}$"
)


# # #
kable(Table2,
  digits = 2,
  format = "latex",
  align = "lllrccrcc",
  escape = FALSE,
  row.names = FALSE,
  booktabs = T,
  linesep = "",
  caption = "Geographic Evenness and Richness of lead authors publishing Open Access (i.e., OA) articles in Mirror and Parent journals vs. subscription-only, non-OA, articles in Parent journals (Psub). The value for Psub is the mean of 1000 bootstrap-generated article collections identical in size and structure to each OA group with which they are being compared (i.e., OA in Mirror, OA in Parent). Single: authors of single-authored articles; First: first authors of co-authored articles."
) %>%
  kable_styling(
    bootstrap_options = c("hover"),
    # full_width = F,
    latex_options = c("scale_down"),
    # latex_options = c("hold_position"),
    font_size = 12,
    position = "center"
  ) %>%
  add_header_above(c(" " = 3, "All Countries" = 3, "China & USA Excluded" = 3))
```
