 ---
title: "Smith et al. Appendix"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document

fig_caption: no #yes will automatically add "Figure X" to the start 
# of the caption and reorders automatically if the figure position changes
always_allow_html: yes

# These are LaTex settings to take care of floating figures/tables, line spacing, etc
header-includes:
  - \usepackage{endfloat} #[nomarkers] excludes the {insert figure x around here] from main text. The others exclude the list of tables and figures. https://cs.brown.edu/about/system/managed/latex/doc/endfloat.pdf
  - \usepackage{setspace}\doublespacing
  - \usepackage{lineno}
  - \linenumbers
# 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)

library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(kableExtra)
library(readr)
```

```{r cached=TRUE}
knitr::opts_chunk$set(echo = FALSE)

MirrorPairs<-read.csv("./data_clean/MirrorPairs.csv")
WaiverCountries<-read.csv("./data_clean/WaiverCountries.csv")

AllData<-read_csv(file="./data_clean/all_data_analysis.csv")
AllData_missing<-AllData %>%
  filter(AuthorNum==1) %>%
  filter(is.na(First_Author_Country)) %>%
  select(refID)
AllData<-AllData %>% filter(!refID %in% AllData_missing$refID)
rm(AllData_missing)

sole_author_pubs_ALL <-read_csv("./data_clean/one_author_pubs_ALL.csv")

coauthor_pubs_ALL<-read_csv("./data_clean/coauthor_pubs_ALL.csv")

sole_author_pubsNOCHNUSA_first_author<-read_csv("./data_clean/one_author_pubsNOCHNUSA.csv")

coauthor_pubsNOCHNUSA_first_author<-read_csv("./data_clean/coauthor_pubsNOCHNUSA.csv")

sole_author_pubs_ALL_first_author<-read_csv("./data_clean/sole_author_pubs_ALL_first_author.csv")

coauthor_pubs_ALL_first_author<-read_csv("./data_clean/coauthor_pubs_ALL_first_author.csv")

bootstrap_results<-read_csv('./output/bootstrap_results.csv')

bootstrap_results_countries<-read_csv("./output/bootstrap_results_countries.csv")

Table2.2<-read.csv('./output/Table2.2.csv')


```

```{r npapers, echo=FALSE,message = FALSE,warning=FALSE}
NumbArticles_JrnlType <- AllData %>% #number of papers per journal
  group_by(JrnlType) %>%
  summarize(n=n_distinct(refID))

NumbSoloArticles_JrnlType<-sole_author_pubs_ALL %>%
group_by(JrnlType) %>%
  summarize(n=n_distinct(refID))

NumbCoAuthoredArticles_JrnlType<-coauthor_pubs_ALL %>%
group_by(JrnlType) %>%
  summarize(n=n_distinct(refID))

n_OA<-NumbArticles_JrnlType[1,2]
n_PW<-NumbArticles_JrnlType[2,2]
Total_pubs<-n_OA+n_PW
```

```{r rich_div_figs1, echo=FALSE,message = FALSE,warning=FALSE}
knitr::opts_knit$set(eval.after = "fig.cap")
insert_custom1<-n_OA
insert_custom2<-n_PW
```

```{r rich_div_figs, echo=FALSE,message = FALSE,warning=FALSE}
source("./Rscript/functions_figures/CountryPlot.R")
p1<-CountryPlot(sole_author_pubs_ALL_first_author,"author_first","OA")
p2<-CountryPlot(sole_author_pubs_ALL_first_author,"author_first","PW")
p3<-CountryPlot(coauthor_pubs_ALL_first_author,"author_first","OA")
p4<-CountryPlot(coauthor_pubs_ALL_first_author,"author_first","PW")
```

```{r Appendix3,fig.align='center',fig.cap="Appendix 3: Percentage of lead authors based in different countries. Includes both paywalled and open access journals; 'lead authors' are both the authors of sole-authored papers and first authors of co-authored papers."}
source("./Rscript/functions_figures/AppFig1.R") 
AppFig1(AllData)
```

```{r Appendix2,fig.align='center', fig.cap=paste("Appendix 2: Author Geographic Diversity (Shannon Index) for N = ", insert_custom1, " Open Access articles (red bar) and 1000 identically sized collections of Paywalled articles selected by bootstrapping from a pool of ",insert_custom2, " articles.  The black line indicates the mean value for the 1000 bootstrap collections."),fig.fullwidth=TRUE}
source("./Rscript/functions_figures/DivBootFig_shannon.R") 
DivBootFig_shannon(bootstrap_results)
```

```{r Appendix4, fig.align='center', fig.cap=paste("Appendix 4: Geographic Evenness for N = ", insert_custom1, " Open Access articles (red bar) and 1000 identically sized collections of Paywalled articles selected by bootstrapping from a pool of ",insert_custom2, " articles. The black line indicates the mean value for the 1000 bootstrap collections."), fig.fullwidth=TRUE}
source("./Rscript/functions_figures/EvenFig.R") 
EvenFig(bootstrap_results)
```
